name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v1
      with:
        registry: betterftaacr.azurecr.io
        username: betterftaacr
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        push: true
        tags: betterftaacr.azurecr.io/backend:latest
        cache-from: type=registry,ref=betterftaacr.azurecr.io/backend:buildcache
        cache-to: type=registry,ref=betterftaacr.azurecr.io/backend:buildcache,mode=max

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'better-fta-backend'
        publish-profile: ${{ secrets.BACKEND_PUBLISH_PROFILE }}
        images: 'betterftaacr.azurecr.io/backend:latest'