# backend-deploy.yml
name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production – better-fta
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: './backend/requirements.txt'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v1
      with:
        registry: betterftaacr.azurecr.io
        username: betterftaacr
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: |
          betterftaacr.azurecr.io/backend:latest
          betterftaacr.azurecr.io/backend:${{ github.sha }}
        cache-from: type=registry,ref=betterftaacr.azurecr.io/backend:buildcache
        cache-to: type=registry,ref=betterftaacr.azurecr.io/backend:buildcache,mode=max

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'better-fta-backend'
        publish-profile: ${{ secrets.BACKEND_PUBLISH_PROFILE }}
        images: 'betterftaacr.azurecr.io/backend:${{ github.sha }}'