name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v1
      with:
        registry: betterftaacr.azurecr.io
        username: betterftaacr
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        push: true
        tags: betterftaacr.azurecr.io/frontend:latest
        cache-from: type=registry,ref=betterftaacr.azurecr.io/frontend:buildcache
        cache-to: type=registry,ref=betterftaacr.azurecr.io/frontend:buildcache,mode=max

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'better-fta-frontend'
        publish-profile: ${{ secrets.FRONTEND_PUBLISH_PROFILE }}
        images: 'betterftaacr.azurecr.io/frontend:latest'